"""add admin user profile fields

Revision ID: 5e9056de68eb
Revises: de55d609799e
Create Date: 2026-06-15 21:13:30.218701
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9056de68eb'
down_revision: Union[str, None] = 'de55d609799e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('admin_users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('admin_users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('admin_users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'reset_token_expires')
    op.drop_column('admin_users', 'reset_token')
    op.drop_column('admin_users', 'email')
    op.drop_column('admin_users', 'display_name')
    # ### end Alembic commands ###
