"""initial_schema

Revision ID: aabee4bd2a9d
Revises: 
Create Date: 2026-03-28 19:22:37.004164
"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabee4bd2a9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportes_emergencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_reportante', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_from', sa.String(length=50), nullable=False),
    sa.Column('direccion_hechos', sa.String(length=500), nullable=True),
    sa.Column('direccion_persona', sa.String(length=500), nullable=True),
    sa.Column('tipo_de_emergencia', sa.Enum('incendio_forestal', 'tala_ilegal', 'contaminacion_agua', 'contaminacion_aire', 'vertimiento_residuos', 'maltrato_animal', 'ruido_excesivo', 'invasion_zona_protegida', 'derrumbe', 'inundacion', 'otro', name='tipo_emergencia_enum', create_constraint=True), nullable=False),
    sa.Column('descripcion_emergencia', sa.Text(), nullable=False),
    sa.Column('descripcion_detallada', sa.Text(), nullable=False),
    sa.Column('ubicacion_inferida', sa.String(length=500), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('nivel_de_gravedad', sa.Enum('alta', 'media', 'baja', name='nivel_gravedad_enum', create_constraint=True), nullable=False),
    sa.Column('requiere_atencion_inmediata', sa.Boolean(), nullable=False),
    sa.Column('texto_original', sa.Text(), nullable=True),
    sa.Column('fuente', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # geoalchemy2 crea el índice GIST automáticamente en la columna geom
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportes_emergencia')
    # ### end Alembic commands ###
