"""add_seguimiento_historial

Revision ID: c199d85ca8af
Revises: d6411f695d84
Create Date: 2026-06-15 19:10:10.829508
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c199d85ca8af'
down_revision: Union[str, None] = 'd6411f695d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporte_historial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporte_id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('campo', sa.String(length=50), nullable=True),
    sa.Column('valor_anterior', sa.String(length=255), nullable=True),
    sa.Column('valor_nuevo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporte_id'], ['reportes_emergencia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reporte_seguimiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporte_id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporte_id'], ['reportes_emergencia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reporte_seguimiento')
    op.drop_table('reporte_historial')
    # ### end Alembic commands ###
